/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences/index'
import { Route as ExperiencesYoutubeIndexRouteImport } from './routes/experiences/youtube/index'
import { Route as ExperiencesYoutubeThemesThemeIdRouteImport } from './routes/experiences/youtube/themes/$themeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesYoutubeIndexRoute = ExperiencesYoutubeIndexRouteImport.update({
  id: '/experiences/youtube/',
  path: '/experiences/youtube/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesYoutubeThemesThemeIdRoute =
  ExperiencesYoutubeThemesThemeIdRouteImport.update({
    id: '/experiences/youtube/themes/$themeId',
    path: '/experiences/youtube/themes/$themeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/experiences/youtube': typeof ExperiencesYoutubeIndexRoute
  '/experiences/youtube/themes/$themeId': typeof ExperiencesYoutubeThemesThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/experiences/youtube': typeof ExperiencesYoutubeIndexRoute
  '/experiences/youtube/themes/$themeId': typeof ExperiencesYoutubeThemesThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/experiences/youtube/': typeof ExperiencesYoutubeIndexRoute
  '/experiences/youtube/themes/$themeId': typeof ExperiencesYoutubeThemesThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiences'
    | '/experiences/youtube'
    | '/experiences/youtube/themes/$themeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiences'
    | '/experiences/youtube'
    | '/experiences/youtube/themes/$themeId'
  id:
    | '__root__'
    | '/'
    | '/experiences/'
    | '/experiences/youtube/'
    | '/experiences/youtube/themes/$themeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  ExperiencesYoutubeIndexRoute: typeof ExperiencesYoutubeIndexRoute
  ExperiencesYoutubeThemesThemeIdRoute: typeof ExperiencesYoutubeThemesThemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/youtube/': {
      id: '/experiences/youtube/'
      path: '/experiences/youtube'
      fullPath: '/experiences/youtube'
      preLoaderRoute: typeof ExperiencesYoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/youtube/themes/$themeId': {
      id: '/experiences/youtube/themes/$themeId'
      path: '/experiences/youtube/themes/$themeId'
      fullPath: '/experiences/youtube/themes/$themeId'
      preLoaderRoute: typeof ExperiencesYoutubeThemesThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  ExperiencesYoutubeIndexRoute: ExperiencesYoutubeIndexRoute,
  ExperiencesYoutubeThemesThemeIdRoute: ExperiencesYoutubeThemesThemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
